import json
from src.Memory import Memory
import os
import datetime
from typing import Optional

BACKUP_DIRECTORY = './tmp/backups'
os.makedirs(BACKUP_DIRECTORY, exist_ok=True)

class Story():
    def __init__(self, story_template_directory: str, saves_directory: str):

        self.story_template_path = story_template_directory

        # Look for config story.json file (Other files are loaded by the system prompt compiler not here)
        if  os.path.exists(f"{story_template_directory}/story.json"):
            with open(f"{story_template_directory}/story.json", "r") as f:
                config_file = json.load(f)
        else:
            raise FileNotFoundError(f"story.json not found in {story_template_directory}. This is required to load the story template.")

        # Hydrate a new story object
        self.title = config_file.get("title", "Untitled Story")
        self.messages: list[Message] = []
        self.messages.append(Message("System", config_file.get("initial_prompt", "")))
        self.memory = Memory()
        self.turn_number = 0
        self.message_cutoff_index = 0
        self.last_time_est = 'STORY START, no time has passed yet'
        self.inventory = config_file.get("initial_inventory", "No inventory it should be generated by the agent based on the story template and initial prompt.")
        self.plan = None
        self.config = config_file.get("config", {})   
        self.number_of_backups_to_keep = self.config.get("number_of_backups_to_keep", 3)

        # Make save location
        os.makedirs(saves_directory, exist_ok=True)
        
        safe_title = "".join(c if c.isalnum() or c in ('-', '_') else '_' for c in self.title)
        self.load_path = os.path.join(saves_directory, f"{datetime.datetime.now().strftime('%Y-%m-%d %H-%M-%S')}_{safe_title}.json")
        
        
    @classmethod
    def load(cls, filename_path: str):
        with open(filename_path, 'r') as f:
            data = json.load(f)
            return cls.from_dict(data, filename_path)

    def to_dict(self):
        return {
            "title": self.title,
            "story_template": self.story_template_path,
            "memory": self.memory.to_dict(),
            "turn_number": self.turn_number,
            "message_cutoff_index": self.message_cutoff_index,
            "last_time_est": self.last_time_est,
            "inventory": self.inventory,
            "messages": [m.to_dict() for m in self.messages]
        }

    @classmethod
    def from_dict(cls, data, load_path: str):
        story = cls(data.get("story_template", ""), os.path.dirname(data.get("load_path", "stories/")))
        story.load_path = load_path #overwrite the default load path

        story.title = data.get("title", "Untitled Story")
        story.memory.from_dict(data.get("memory", {}))
        story.turn_number = data.get("turn_number", 0)
        story.message_cutoff_index = data.get("message_cutoff_index", 0)
        story.last_time_est = data.get("last_time_est", 'STORY START, no time has passed yet')
        story.inventory = data.get("inventory", "No inventory it should be generated by the agent based on the story template and initial prompt.")
        story.messages = [Message.from_dict(m) for m in data.get("messages", [])]
        return story

    def save(self, filename: str = None):
        if filename is None:
            filename = self.load_path

        # Only rotate backups if a valid save already exists.
        if  os.path.exists(filename):
            self.__rotate_backups_forwards(filename)

        with open(filename, 'w') as f:
            json.dump(self.to_dict(), f, indent=4)

        return

    def restore_from_backup(self) -> Optional['Story']: # Have to use Optional to self reference Story type
        if self.__rotate_backups_backwards():
            return Story.load(self.load_path)
        else:
            return None

    def __rotate_backups_forwards(self, file_path: str):

        filename_only = os.path.basename(file_path)

        # Find the oldest backup we have
        oldest_backup_index = None
        for i in range(self.number_of_backups_to_keep - 1, -1, -1):
            oldest_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i}")
            if os.path.exists(oldest_backup):
                oldest_backup_index = i
                break # The first backup we find is the oldest

        # If we have backups we need to rotate them forwards to make room for the new backup.
        # If we have room we can make a new backup
        if oldest_backup_index is not None:
            if oldest_backup_index < self.number_of_backups_to_keep - 1:
                oldest_backup_index += 1 # We can add a backup because we haven't hit our max yet.

            for i in range(oldest_backup_index, 0, -1):
                older_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i-1}")
                newer_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i}")
                if os.path.exists(older_backup) or older_backup == os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup0"):
                    if os.path.exists(newer_backup):
                        os.remove(newer_backup)
                    os.rename(older_backup, newer_backup)

        if os.path.exists(self.load_path): # Write the current save to the backup0 slot
            if os.path.exists(os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup0")):
                os.remove(os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup0"))
            os.rename(self.load_path, os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup0"))



    def __rotate_backups_backwards(self) -> bool:

        # 1. Check to see if backup0 exists, if not return false (can't restore)
        filename_only = os.path.basename(self.load_path)
        backup_path = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup0")
        if not os.path.exists(backup_path):
            return False
        
        # 2. Restore from backup0
        if os.path.exists(self.load_path):
            os.remove(self.load_path)
        os.rename(backup_path, self.load_path)

        # 3. Rotate backups backwards so that backup1 becomes backup0, backup2 becomes backup1, etc.
        for i in range(1, self.number_of_backups_to_keep):
            older_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i-1}")
            newer_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i}")
            if os.path.exists(newer_backup):
                os.rename(newer_backup, older_backup)

        # Find the oldest backup we have
        oldest_backup_index = None
        for i in range(self.number_of_backups_to_keep - 1, 0, -1):
            oldest_backup = os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{i}")
            if os.path.exists(oldest_backup):
                oldest_backup_index = i
                break # The first backup we find is the oldest

        # Delete the oldest backup
        if oldest_backup_index is not None:
            os.remove(os.path.join(BACKUP_DIRECTORY, f"{filename_only}.backup{oldest_backup_index}"))

        return True
        

class Message():
    def __init__(self, agent_name: str = "", content: str = ""):
        self.content = content
        self.agent_name = agent_name

    def to_dict(self):
        return {
            "agent_name": self.agent_name,
            "content": self.content
        }

    @classmethod
    def from_dict(cls, data):
        return cls(
            agent_name=data.get("agent_name", ""),
            content=data.get("content", "")
        )